// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCswf_pFS4ZxKavsMGEK-4olojhuTNo5TU',
    appId: '1:603568524649:web:5e4161e9c4ac5e468881f8',
    messagingSenderId: '603568524649',
    projectId: 'mindsprint-2aa78',
    authDomain: 'mindsprint-2aa78.firebaseapp.com',
    storageBucket: 'mindsprint-2aa78.firebasestorage.app',
    measurementId: 'G-L1447H1ESJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8FfDouKfzNyG2jaNJCWggTIg7WzmXeIM',
    appId: '1:603568524649:android:072cba5489baf1838881f8',
    messagingSenderId: '603568524649',
    projectId: 'mindsprint-2aa78',
    storageBucket: 'mindsprint-2aa78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1WwJJDzPOSjJynhFJNVsPXTrzsfyjblA',
    appId: '1:603568524649:ios:016cb9287560953c8881f8',
    messagingSenderId: '603568524649',
    projectId: 'mindsprint-2aa78',
    storageBucket: 'mindsprint-2aa78.firebasestorage.app',
    iosBundleId: 'com.example.mindsprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1WwJJDzPOSjJynhFJNVsPXTrzsfyjblA',
    appId: '1:603568524649:ios:016cb9287560953c8881f8',
    messagingSenderId: '603568524649',
    projectId: 'mindsprint-2aa78',
    storageBucket: 'mindsprint-2aa78.firebasestorage.app',
    iosBundleId: 'com.example.mindsprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCswf_pFS4ZxKavsMGEK-4olojhuTNo5TU',
    appId: '1:603568524649:web:e24b68323201a4538881f8',
    messagingSenderId: '603568524649',
    projectId: 'mindsprint-2aa78',
    authDomain: 'mindsprint-2aa78.firebaseapp.com',
    storageBucket: 'mindsprint-2aa78.firebasestorage.app',
    measurementId: 'G-ZSTB4WMWFG',
  );
}
